sudo: false
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: SYMFONY_VERSION=4.0.*
  - php: 7.1
    env: SYMFONY_VERSION=4.0.*

before_script:
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e "create database symfony;"
  - mysql -e "set global wait_timeout=600"
  - composer self-update
  - rm composer.lock # Prevent dependency problems
  - travis_retry composer require "symfony/symfony:${SYMFONY_VERSION}"
  - sed -i 's/utf8mb4/utf8/' Resources/config/aimeos_shop.yml

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls
